### ISSUE TITLE
Could not load type exception 

### ISSUE THREAD

**Issue by su-rabbit** [roryprimrose/Divergic.Logging.Xunit#21]
Hello there,

```
Could not load type 'Microsoft.Extensions.Logging.Internal.FormattedLogValues' from assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```

After My project update version to ASP.NET Core 3.0, Tests failed with above logs.

#20 maybe resolve this problem. But, How about mange reference version as strictly?
Reference : [Dependency Version Range](https://docs.microsoft.com/ko-kr/nuget/concepts/package-versioning)

For example, change
`<PackageReference Include="Microsoft.Extensions.Logging" Version="2.2.0" />` to
`<PackageReference Include="Microsoft.Extensions.Logging" Version="[2.2.0, 3.0.0)" />`

Thank you!

**Comment by roryprimrose** [comment]
I've just pushed 3.3.0 with updated references. Does that fix the issue?
