### ISSUE TITLE
Are there supposed to be blank lines between each line output?

### ISSUE THREAD

**Issue by KevinSmall** [roryprimrose/Divergic.Logging.Xunit#68]
More a question than an issue.  This screenshot shows the output I see from a test runner, and each log entry written using `logger.LogInformation()` has an extra blank line:

![image](https://user-images.githubusercontent.com/5543867/95314178-e1b14e00-0888-11eb-8d4b-c69fd638a55f.png)

Everything seems to work fine, but the output files are twice as long as they need to be, and lots of scrolling up and down ensues.

Is the extra blank line intended, is it configurable to remove it?

**Comment by roryprimrose** [comment]
I actually prefer the whitespace because I like the visual break between log messages. It shouldn't however be there OOTB and people can write their own formatter if they want that whitespace in there.
